version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY}/kickof-server:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY}/kickof-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped